#
# Copyright (c) 2023 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
[package]
authors = [
  "ZettaScale Zenoh Team <zenoh@zettascale.tech>"
]
description = "Internal crate for zenoh."
edition = "2021"
homepage = "http://zenoh.io"
license = "EPL-2.0 OR Apache-2.0"
name = "zenoh-pinned-deps"
repository = "https://github.com/eclipse-zenoh/zenoh"
rust-version = "1.75.0"
version = "1.5.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
base64ct = "=1.6.0"
home = "=0.5.9"
jsonschema = { version = "=0.20.0", default-features = false }
lz4_flex = "=0.11.3"
static_init = "=1.0.3"
twox-hash = "=1.6.3"
url = "=2.5.2"
pest = "=2.7.12"
pest_derive = "=2.7.12"
pest_meta = "=2.7.12"
pest_generator = "=2.7.12"
thiserror = "=1.0.69"




